spring:
    mvc:
        favicon:
            enabled: false
    profiles:
        active: dev
    thymeleaf:
        cache: false


mybatis:  #mybatis整合信息
    config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis所在路径
    type-aliases-package: com.zhangju.manage.entiry #entity别名类
    mapper-locations:
    - classpath:mybatis/mapper/*.xml #mapper映射文件