#端口
server:
    port: 8080
##############################url调用接口参数##############################
spring:
    session:
        store-type: redis
        redis:
            host: 192.168.16.4
            port: 6379
            password: zhangju123