#端口
server:
    port: 8888
##############################url调用接口参数##############################
spring:
    session:
        timeout: 10s
        store-type: redis
    redis:
        timeout: 10s
        host: 106.12.17.202
        port: 6379
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: resume
        url: jdbc:mysql://106.12.17.202:3306/resume?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: zhangju123